name: Build and deploy the blog

on:
  push:
    branches: [ "master" ]
    paths:
      - "blogs/**"
      - "journal/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: docusaurus/package-lock.json

    - name: Install and Build
      run: |
        npm ci
        npm run build
      working-directory: docusaurus

    - name: Deploy
      run: |
        npm run deploy
      working-directory: docusaurus
      env:
        GIT_USER: github-actions
        GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
